// =================================================================
// SafeRoute Backend — PM2 Process Manager Configuration
// Target: Hostinger KVM 2 (Node.js / Express / Socket.IO)
// =================================================================

module.exports = {
  apps: [
    {
      name: 'saferoute-backend',
      // Note: Points to the verified compiled output generated by "npm run build"
      script: 'dist/index.js',
      cwd: __dirname,
      // Fork mode is recommended for stateful Socket.IO in-memory rooms without a Redis adapter
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
        HOST: '127.0.0.1',
      },
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
    },
  ],
};
